### ISSUE TITLE
Fails To Add As Dependency

### ISSUE THREAD

**Issue by AtropineTears** [marirs/winfw-rs#1]
Hi,

when inserting:

```toml
[target.'cfg(windows)'.dependencies]
winfw = "0.1.1"
```

into my dependencies it comes up with a build error

```
failed to run custom build command for `winfw v0.1.1`
```
